import { translations } from "./i18n";

// Commercial UI copy layer: keep operational data and actions visible,
// remove tutorial-like, repetitive, and implementation-specific wording.
Object.assign(translations.id, {
  subtitle: "Operations",
  shiftActive: "Shift 1",
  cloudFirestore: "ONLINE",
  authorityLogin: "Login",
  switchAuthority: "Ganti User",
  logout: "Keluar",
  simulateCall: "+ Simulasi",
  soundActive: "Alarm Aktif",
  soundMuted: "Alarm Senyap",

  quickGuideTitle: "Panduan",
  quickGuideSubtitle: "",
  step1Title: "Operator",
  step1Desc: "",
  step2Title: "Andon",
  step2Desc: "",
  step3Title: "Responder",
  step3Desc: "",
  step4Title: "Riwayat",
  step4Desc: "",
  hideGuide: "Tutup",
  showGuide: "Panduan",

  plantStatus: "Status Plant",
  plantSmooth: "Normal",
  immediateResponseNeeded: "Perlu Respon",
  zeroLineStop: "0 Line Stop",
  ticketsInProgress: "WO Dalam Penanganan",
  avgOee: "OEE Shift",
  targetOee: "Target > 85%",
  productionLinesStatus: "Status Line",
  allRunningSmooth: "Normal",
  activeAndonCallsTitle: "Panggilan Aktif",
  requiresImmediateAction: "Perlu Respon",
  noActiveCalls: "Tidak ada panggilan aktif.",
  resolvedTodayTitle: "Riwayat Hari Ini",
  resolvedTicketsCount: "WO Selesai",
  noResolvedCalls: "Belum ada WO selesai.",

  operatorTerminalTitle: "Operator Andon",
  operatorTerminalSubtitle: "",
  step1SelectStation: "Stasiun Kerja · {lineName}",
  step2SelectCategory: "Kategori Andon",
  step3Details: "Detail Panggilan",
  lineStopCondition: "Line Stop",
  lineStopSubtext: "",
  severityLevel: "Severity",
  severityTitle: "Severity",
  problemNotesLabel: "Catatan (Opsional)",
  problemNotesPlaceholder: "",
  sendAndonCallBtn: "KIRIM PANGGILAN",
  sendAndonCallSubtext: "",
  activeCallAtStation: "PANGGILAN AKTIF",
  cancelOrResolvedBtn: "Batalkan / Selesai",
  callSuccessAlert: "Panggilan Dibuat",
  callSuccessDesc: "",
  selectLine: "Line Produksi",
  selectCategory: "Kategori",
  selectWorkstation: "Stasiun Kerja",
  selectProblemCategory: "Kategori",
  problemDesc: "Deskripsi",

  responderTitle: "Responder",
  responderSubtitle: "",
  responderDashboardTitle: "Responder",
  responderDashboardSubtitle: "",
  searchPlaceholder: "Cari WO, line, stasiun...",
  resolvedTicketsFilter: "Selesai",
  noTicketsFound: "Tidak Ada WO",
  noTicketsSubtext: "Tidak ada data.",
  acknowledgeBtn: "Terima",
  respondCallBtn: "Terima",
  startRepairBtn: "Mulai Perbaikan",
  directResolveBtn: "Selesai",
  resolveAnd5WhyBtn: "Selesaikan & Catat",
  resolveModalTitle: "Penutupan WO",
  rootCauseLabel: "Akar Masalah",
  actionTakenLabel: "Tindakan Perbaikan",
  correctiveAction: "Tindakan Perbaikan",
  fiveWhySectionTitle: "5-Why",
  saveAndNormalizeBtn: "Simpan & Selesai",

  plantMapTitle: "Peta Plant",
  plantMapSubtitle: "",
  legendTower: "Legenda Andon",
  selectLineFilter: "Line Produksi",
  allLines: "Semua Line",
  clickStationToCall: "",

  masterDataTitle: "Master Data",
  masterDataSubtitle: "",
  uploadMasterData: "Import Excel / CSV",
  masterLinesTab: "Line",
  masterMachinesTab: "Mesin",
  templateAndGuideTab: "Template CSV",
  masterCleanTab: "Data Trial",
  databaseMasterLinesTitle: "Master Line",
  addNewLineBtn: "+ Tambah Line",
  databaseMasterMachinesTitle: "Master Mesin",
  noMachineData: "Belum ada data mesin.",
  templateMasterLinesDesc: "",
  templateMasterMachinesDesc: "",
  bulkUploadTitle: "Import Data",
  bulkUploadDesc: "",
  dropFileHere: "Excel / CSV",
  supportedFormats: ".xlsx · .xls · .csv",
  uploadSuccess: "Import Berhasil",
  addNewLineTitle: "Tambah Line",
  lineListTitle: "Daftar Line",
  deleteLineConfirm: "Hapus line ini?",

  activityLogsTitle: "Activity Log",
  activityLogsSubtitle: "",
  filterActionLabel: "Jenis Aksi",
  searchLogsPlaceholder: "Cari aktivitas, petugas, WO...",
  noLogsFound: "Belum Ada Aktivitas",

  analyticsTitle: "Analytics",
  analyticsSubtitle: "",
  paretoDowntimeTitle: "Pareto Downtime per Line",
  dailyTrendTitle: "Tren Andon 7 Hari",
  exportReportBtn: "Ekspor CSV",

  aiModalSubtitle: "",
  aiAssistantSubtitle: "",
});

Object.assign(translations.en, {
  subtitle: "Operations",
  shiftActive: "Shift 1",
  cloudFirestore: "ONLINE",
  authorityLogin: "Login",
  switchAuthority: "Switch User",
  logout: "Logout",
  simulateCall: "+ Simulate",
  soundActive: "Alarm On",
  soundMuted: "Alarm Muted",

  quickGuideTitle: "Guide",
  quickGuideSubtitle: "",
  step1Title: "Operator",
  step1Desc: "",
  step2Title: "Andon",
  step2Desc: "",
  step3Title: "Responder",
  step3Desc: "",
  step4Title: "History",
  step4Desc: "",
  hideGuide: "Close",
  showGuide: "Guide",

  plantStatus: "Plant Status",
  plantSmooth: "Normal",
  immediateResponseNeeded: "Response Required",
  zeroLineStop: "0 Line Stop",
  ticketsInProgress: "WO In Progress",
  avgOee: "Shift OEE",
  targetOee: "Target > 85%",
  productionLinesStatus: "Line Status",
  allRunningSmooth: "Normal",
  activeAndonCallsTitle: "Active Calls",
  requiresImmediateAction: "Response Required",
  noActiveCalls: "No active calls.",
  resolvedTodayTitle: "Today's History",
  resolvedTicketsCount: "WO Closed",
  noResolvedCalls: "No closed WO.",

  operatorTerminalTitle: "Operator Andon",
  operatorTerminalSubtitle: "",
  step1SelectStation: "Workstation · {lineName}",
  step2SelectCategory: "Andon Category",
  step3Details: "Call Details",
  lineStopCondition: "Line Stop",
  lineStopSubtext: "",
  severityLevel: "Severity",
  severityTitle: "Severity",
  problemNotesLabel: "Notes (Optional)",
  problemNotesPlaceholder: "",
  sendAndonCallBtn: "SEND CALL",
  sendAndonCallSubtext: "",
  activeCallAtStation: "ACTIVE CALL",
  cancelOrResolvedBtn: "Cancel / Resolve",
  callSuccessAlert: "Call Created",
  callSuccessDesc: "",
  selectLine: "Production Line",
  selectCategory: "Category",
  selectWorkstation: "Workstation",
  selectProblemCategory: "Category",
  problemDesc: "Description",

  responderTitle: "Responder",
  responderSubtitle: "",
  responderDashboardTitle: "Responder",
  responderDashboardSubtitle: "",
  searchPlaceholder: "Search WO, line, station...",
  resolvedTicketsFilter: "Resolved",
  noTicketsFound: "No WO",
  noTicketsSubtext: "No data.",
  acknowledgeBtn: "Acknowledge",
  respondCallBtn: "Acknowledge",
  startRepairBtn: "Start Repair",
  directResolveBtn: "Resolve",
  resolveAnd5WhyBtn: "Resolve & Record",
  resolveModalTitle: "Close WO",
  rootCauseLabel: "Root Cause",
  actionTakenLabel: "Action Taken",
  correctiveAction: "Action Taken",
  fiveWhySectionTitle: "5-Why",
  saveAndNormalizeBtn: "Save & Close",

  plantMapTitle: "Plant Map",
  plantMapSubtitle: "",
  legendTower: "Andon Legend",
  selectLineFilter: "Production Line",
  allLines: "All Lines",
  clickStationToCall: "",

  masterDataTitle: "Master Data",
  masterDataSubtitle: "",
  uploadMasterData: "Import Excel / CSV",
  masterLinesTab: "Lines",
  masterMachinesTab: "Machines",
  templateAndGuideTab: "CSV Template",
  masterCleanTab: "Trial Data",
  databaseMasterLinesTitle: "Master Lines",
  addNewLineBtn: "+ Add Line",
  databaseMasterMachinesTitle: "Master Machines",
  noMachineData: "No machine data.",
  templateMasterLinesDesc: "",
  templateMasterMachinesDesc: "",
  bulkUploadTitle: "Import Data",
  bulkUploadDesc: "",
  dropFileHere: "Excel / CSV",
  supportedFormats: ".xlsx · .xls · .csv",
  uploadSuccess: "Import Complete",
  addNewLineTitle: "Add Line",
  lineListTitle: "Lines",
  deleteLineConfirm: "Delete this line?",

  activityLogsTitle: "Activity Log",
  activityLogsSubtitle: "",
  filterActionLabel: "Action",
  searchLogsPlaceholder: "Search activity, user, WO...",
  noLogsFound: "No Activity",

  analyticsTitle: "Analytics",
  analyticsSubtitle: "",
  paretoDowntimeTitle: "Downtime Pareto by Line",
  dailyTrendTitle: "7-Day Andon Trend",
  exportReportBtn: "Export CSV",

  aiModalSubtitle: "",
  aiAssistantSubtitle: "",
});
